version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 3019:3000
    environment:
      - NEXT_PUBLIC_CHAT_API=http://localhost:8003/api/chat
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: unless-stopped
    ports:
      - 8003:8001
